### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by CptPlastic** [sbaudoin/sonar-yaml#10]
This may be something I am doing but no matter what regexp I put I cant evaluate after a tag.
In the custom rule screen is has this.
key-name | 
Regexp that matches the forbidden name

In this case I want to evaluate the password key. I want to insure that passwords are setup as variables. If I put "password" it will trigger and that is good. However, if I add a regexp to check whats after that it will never work. Is this actually using regexp or something else?

My regex looks like `/password: "[^{{]*/igs`

**Comment by CptPlastic** [comment]
That would be amazing to have ForbbenValueCheck rule. I dont know if this is in scope but I think it would be helpful to have that ability to evaluate after the :

You basically nailed my issue on the head as I just evaluate forbidden keys.

**Comment by sbaudoin** [comment]
OK, so let's try to write this new rule. Planned for release 1.3.0.

**Comment by sbaudoin** [comment]
Hi. Version 1.3.0 just released. enjoy!

**Comment by CptPlastic** [comment]
You sir are AWESOME!

**Comment by CptPlastic** [comment]
This seems to work. It would be nice if it were a template like the other rule so someone could set it if its a vulnerability or code smell ex ex.
