### ISSUE TITLE
Ansible vault encryption variable support

### ISSUE THREAD

**Issue by axel3rd** [sbaudoin/sonar-yaml#15]
Hello, 

When you encrypt some variable with [Ansible vault](https://docs.ansible.com/ansible/user_guide/vault.html), the result in YAML file is like:

```
appli_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          42424242424242424242424242424242424242424242424242424242424242424242424242424242
          42424242424242424242424242424242424242424242424242424242424242424242424242424242
          42424242424242424242424242424242424242424242424242424242424242424242424242424242
          42424242424242424242424242424242424242424242424242424242424242424242424242424242
          4242 
```

This usage occurs a "*Parse error: syntax error: Can't construct a java object for !vault; exception=Invalid tag: !vault*" error (rule : `yaml:ParsingErrorCheck`).

Plugin version : 1.4.0

**Comment by axel3rd** [comment]
See. #19, even if [snakeyaml](https://bitbucket.org/asomov/snakeyaml) 1.24 is used, this tag can't be parsed.

**Comment by axel3rd** [comment]
snakeyaml bugtrack ref: [#435](https://bitbucket.org/asomov/snakeyaml/issues/435/invalid-tag-vault-on-ansible-inventory)

**Comment by sbaudoin** [comment]
This is actually a bug from the underlying YAML linter: see https://github.com/sbaudoin/yamllint/issues/8. I'll need to fix this bug first then repackage the Sonar plugin with the new linter version.
