### ISSUE TITLE
Out of memory exception when running scanner

### ISSUE THREAD

**Issue by MattCodd2** [sbaudoin/sonar-yaml#4]
The scanner throws an OutOfMemory exception when scanning the attached file, even when Sonar is given a 5GB heap size

[ERROR] Java heap space -> [Help 1]
14:57:29 java.lang.OutOfMemoryError: Java heap space
14:57:29 	at org.yaml.snakeyaml.error.Mark.toCodePoints(Mark.java:35)
14:57:29 	at org.yaml.snakeyaml.error.Mark.<init>(Mark.java:45)
14:57:29 	at com.github.sbaudoin.yamllint.LintStreamReader.getMark(LintStreamReader.java:87)
14:57:29 	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1847)
14:57:29 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1027)
14:57:29 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchSingle(ScannerImpl.java:1002)
14:57:29 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:390)
14:57:29 	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
14:57:29 	at com.github.sbaudoin.yamllint.LintScanner.peekToken(LintScanner.java:53)
14:57:29 	at com.github.sbaudoin.yamllint.Parser.getTokensOrComments(Parser.java:404)
14:57:29 	at com.github.sbaudoin.yamllint.Parser.getTokensOrCommentsOrLines(Parser.java:429)
14:57:29 	at com.github.sbaudoin.yamllint.Linter.getCosmeticProblems(Linter.java:224)
14:57:29 	at com.github.sbaudoin.sonar.plugins.yaml.checks.YamlLintCheck.validate(YamlLintCheck.java:46)
14:57:29 	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:142)
14:57:29 	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:96)
14:57:29 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
14:57:29 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
14:57:29 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
14:57:29 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
14:57:29 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
14:57:29 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
14:57:29 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
14:57:29 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
14:57:29 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
14:57:29 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
14:57:29 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
14:57:29 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
14:57:29 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
14:57:29 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
14:57:29 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
14:57:29 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
14:57:29 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
[en.zip](https://github.com/sbaudoin/sonar-yaml/files/2515582/en.zip)

**Comment by sbaudoin** [comment]
Hello,

Thanks for reporting the issue, I'll have a look at it. You must add extra memory to the scanner, not SonarQube server. Please refer to [this page](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner#AnalyzingwithSonarQubeScanner-Troubleshooting).

**Comment by MattCodd2** [comment]
Thanks.  I was adding extra memory to the scanner, not the server, apologies for not making that clear.

I've done some more investigation and found the problem seems to be in the empty-values check:

maven debug trace
...
DEBUG] 09:09:07.448 Saving issue: line too long (4761 > 80 characters) (line-length)
[DEBUG] 09:09:07.449 Saving issue: line too long (4257 > 80 characters) (line-length)
[DEBUG] 09:09:07.450 Saving issue: line too long (6268 > 80 characters) (line-length)
[DEBUG] 09:09:07.451 Saving issue: line too long (223 > 80 characters) (line-length)
[DEBUG] 09:09:07.452 Saving issue: missing document start "---" (document-start)
[DEBUG] 09:09:10.692 Analyzing file: nl.yml
[DEBUG] 09:09:10.717 'src/main/resources/nl.yml' generated metadata  with charset 'UTF-8'
[DEBUG] 09:09:10.772 File file:///xxxx/dev/yyy/Components/TestDataGenerator/Person/Core/trunk/src/main/resources/nl.yml has syntax error? false
[DEBUG] 09:09:10.773 Count lines in nl.yml
[DEBUG] 09:09:10.777 Checking rule: yaml:EmptyValuesCheck
[DEBUG] 09:09:10.778 Got RuleProperty @org.sonar.check.RuleProperty(description=Prevents or not empty values in block mappings, type=, defaultValue=false, key=forbid-in-block-mappings)
[DEBUG] 09:09:10.779 Got RuleProperty @org.sonar.check.RuleProperty(description=Prevents or not empty values in flow mappings, type=, defaultValue=false, key=forbid-in-flow-mappings)
[DEBUG] 09:09:10.781 YAMLLint config for rule yaml:EmptyValuesCheck/empty-values: '---
rules:
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false
'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:40 min
[INFO] Finished at: 2018-10-26T09:09:21+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space
    at org.yaml.snakeyaml.error.Mark.toCodePoints (Mark.java:35)
    at org.yaml.snakeyaml.error.Mark.<init> (Mark.java:45)
    at com.github.sbaudoin.yamllint.LintStreamReader.getMark (LintStreamReader.java:87)
    at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain (ScannerImpl.java:1987)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain (ScannerImpl.java:1044)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens (ScannerImpl.java:399)
...
 
This is with a much smaller yaml file that follows the same general format

**Comment by sbaudoin** [comment]
Just to let you know that I'm working on this issue first thing. It is quite tricky to fix, I'll let you know when it is done.

**Comment by sbaudoin** [comment]
I'm going to release a fix soon. May I embed your file en.yml in my code for unit test purpose?

**Comment by MattCodd2** [comment]
Confirmed as working on SonarQube 7.4
