### ISSUE TITLE
Plugin not available in SonarQube 8.1 Marketplace

### ISSUE THREAD

**Issue by alwa** [sbaudoin/sonar-yaml#42]
I cannot see this plugin in the list of available plugins using version 8.1 of SonarQube.

**Comment by sbaudoin** [comment]
Hello,

You might have a problem with the connection to the Internet: I just checked at the latest version of the plugin appears when you search for "yaml".

**Comment by alwa** [comment]
@sbaudoin Ah, yes I probably made a mistake here. 

There were multiple plugins in my setup (6.7) that were no longer available after upgrading (8.1) so I just reported issues in the different github projects without much verification. 

Could it be that the rule repository name for the YAML rules have been changed?

**Comment by sbaudoin** [comment]
No, the repository name has not changed. However there may be some changes in SonarQube itself on the repository side. I tested the upgrade once and did not notice any change.

**Comment by alwa** [comment]
I can confirm. My bad.
