### ISSUE TITLE
How to build this project to a jar file

### ISSUE THREAD

**Issue by fantasticYang** [sbaudoin/sonar-yaml#44]
hi there ,I’m new to this project.May I ask  that how to build this project to a jar file  ,IDE occurs some error when I use  “mvn package”, i wanna put it on the sonar platform .In fact Im trying to make some custom rules to use.

**Comment by sbaudoin** [comment]
Hello,

With no details about the error you meet it's defficult to help. You can see the build details for Travis CI in [.travis.yml](https://github.com/sbaudoin/sonar-yaml/blob/master/.travis.yml).
