### ISSUE TITLE
Vulnerability Found

### ISSUE THREAD

**Issue by rmauc** [sbaudoin/sonar-yaml#45]
Hello
I am very interested in using the Ansible Sonarqube plugin (which has a dependency on this plugin).
However, our security guys ran an XRay scan and found a high vulnerability for qos.logback (attached)

![yamlplugin](https://user-images.githubusercontent.com/18124843/84720694-c2468c00-af4c-11ea-82b3-4a2bbbb4bf81.png)
. 
Would you be able to take a look to determine if you can patch and release a newer version?
That would be very much appreciated if at all possible
Thanks in advance

**Comment by sbaudoin** [comment]
Hello,

Yes, I think I can change that. However I don't know how to check that my fix will be OK: do you know how I could do that?

**Comment by rmauc** [comment]
Hi 
Thanks for getting back to me. I can get my guy to rerun the scan :)

**Comment by rmauc** [comment]
Hello
Do you have anything to test?
Thanks again

**Comment by sbaudoin** [comment]
Hello,

I think it's better if I can check myself the errors: going back and forth with small code change may not be efficient. So is there a way for me to check if my fix is correct?

**Comment by sbaudoin** [comment]
107935b updates the logback dependency to 1.2.3. Hope this is sufficient.

**Comment by reitzmichnicht** [comment]
You can run snyk on your project which should give you the results you expect

**Comment by sbaudoin** [comment]
Thanks. Snyk does not report issue for this project
