### ISSUE TITLE
[question] No YAML failures showing up

### ISSUE THREAD

**Issue by sverhagen** [sbaudoin/sonar-yaml#47]
Thank you for this plugin and thank you for helping with my question! This is probably more of a question than an issue.

We are running SonarQube CE version 7.6. Is this plugin supposed to be compatible?

I did the following:
* Installed the plugin
* Restarted SonarQube
* Committed a broken YAML file in `src/main/resources/application.yaml` (checked with `yamllint`: `error syntax error: expected <block end>, but found '-'`
* Build ran, no errors, no mention of anything YAML-related

Expected result:
* Error showing up in SonarQube

Actual result:
* No mention of YAML in the build
* No errors in the log

"YAML" is shown as a language in SonarQube and the rules are shown (under "Rules"), there's just no data about YAML for my intentional faulty build. The YAML Analyzer plugin is also shown in the General Settings ("File Suffixes", "Filter UTF-8...").

It is my assumption that this should just work with my standard run of `sonar-maven-plugin`, or am I naively ignoring the need to run something like `yamllint` locally?

**Comment by sbaudoin** [comment]
Hello,

During the latest build, the plugin was tested with SQ 6.7, 7.7, 7.8, 7.9 and 8.0 but not with a file that contains a syntax error. However if I install the plugin in a SQ 7.6 box and scan a project with a file containing a syntax error, I can see a "Parse error" being reported.

So can you see the default "Sonar way" quality profile installed and enable as default for the YAML language? If not you must create a profile in which you enable the parse error rule.

**Comment by sbaudoin** [comment]
@sverhagen What can also happen is that the Maven SQ plugin does not analyzes YAML files by default (from [a recent post on the SQ forum](https://community.sonarsource.com/t/sonarqube-ignores-files-in-maven-src-main-resources/22081/3), the plugin only takes into account the HTML, CSS and JS by default). If you want to force SQ to also analyze the YAML files present in `src/main/resources` you have to add this directory into the property `sonar.sources`. Example:

```xml
   <properties>
        <sonar.host.url>http://localhost:9079</sonar.host.url>
        <sonar.sources>src/main/resources/playbooks</sonar.sources>
    </properties>
```

**Comment by sverhagen** [comment]
Yes, this was absolutely _it_. The default for SonarScanner for Maven appears to be this:

    <sonar.sources>src/main/java</sonar.sources>
    <sonar.tests>src/test/java</sonar.tests>

I have now added the following configuration, and that does it:

    <sonar.sources>src/main</sonar.sources>
    <sonar.tests>src/test</sonar.tests>
