### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by sinharitika07** [sbaudoin/sonar-yaml#50]
Is this plugin ready to use? One of our team member had reviewed and found a vulnerability issue reported is yet to fix.

**Comment by sbaudoin** [comment]
Hello,

I don't know yet, I don't have a lot of time to spend on it, unfortunately. Which vulnerability are you referring to?

**Comment by sbaudoin** [comment]
@sinharitika07 if you are referring to #45, it is fixed with [the release v1.5.2](/sbaudoin/sonar-yaml/releases/tag/v1.5.2) of today.
