### ISSUE TITLE
Yamllint configuration option through yamllint

### ISSUE THREAD

**Issue by mcico** [sbaudoin/sonar-yaml#52]
Hey,

We started to use the yaml lint plugin with sonar in an ansible project.

In the project setup we run yamllint from a python virtual environment (version 1.25.0) which is configured with a `.yamllint` configuration file, where we disable some rules we cannot deal with right now (mostly formatting issues).

When running sonar, the yaml code is also analyzed but the configuration from the .yamllint file is ignored.

While checking the documentation it was not clear to me how the sonar yaml plugin behaves. The java library doing the yaml checks respects the file, whereas during the sonar plugin execution it seems to be ignored.

I have seen in other plugins that it is sometimes possible to configure such a configuration explicitly, which I was not able to find for this plugin.

Is there a way to feed such a .yamllint configuration to the sonar-yaml plugin?

cheers & thanks
marco

**Comment by rjpearce** [comment]
I have the same question. According to the [yamllint docs ](https://yamllint.readthedocs.io/en/latest/configuration.html) you can use any of the following locations

```
.yamllint, .yamllint.yaml or .yamllint.yml in the current working directory
the file referenced by $YAMLLINT_CONFIG_FILE, if set
$XDG_CONFIG_HOME/yamllint/config
~/.config/yamllint/config
```

For example if you set the following in: .yamllint.yml 
```
---
extends: default
rules:
  line-length: disable
```
Yamllint will pass successfully but SonarQube will report a code smell if a line is longer than the default line-length. The plugin appears not to be using the configuration file.

@sbaudoin can you shed any light on whether the YAML Lint plugin for SonarQube does indeed read the YAML Lint configuration file?

**Comment by sbaudoin** [comment]
Hello,

Yes indeed, the plugin does not take these files into account. I just forgot to implement this feature: the odd thing is that the Java yamllint lib behind the plugin takes into account the `.yamllint*` files. I'm likely to release a new version of the plugin, I'm going to fix that.
