### ISSUE TITLE
Scan failing on Sonar version 9.4

### ISSUE THREAD

**Issue by dharanitharan-selvaraj** [sbaudoin/sonar-yaml#70]
After upgrading sonar to version 9.4 Our scans are failing with the below error
`ERROR: Error during SonarScanner execution
java.lang.UnsupportedOperationException: Can not add the same measure twice on ci-artifacts/elasticsearch/template.yml: DefaultMeasure[component=ci-artifacts/elasticsearch/template.yml,metric=Metric[uuid=<null>,key=ncloc_data,description=<null>,type=DATA,direction=0,domain=<null>,name=ncloc_data,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>],value=1=1;2=1;3=1;5=1;6=1;7=1;8=1;9=1;10=1;11=1;12=1;13=1;14=1;15=1;16=1;17=1;18=1;19=1;20=1;21=1;22=1;23=1;24=1;25=1;26=1;27=1;28=1;29=1;30=1;31=1;32=1;33=1;34=1;35=1;36=1;37=1;38=1;39=1;40=1;41=1;42=1;43=1;44=1;45=1;46=1;47=1;48=1;50=1;51=1;53=1;73=1;74=1;79=1;80=1;81=1;82=1;83=1;84=1;85=1;86=1;87=1;88=1;89=1;90=1;91=1;92=1;93=1;94=1;95=1;96=1;97=1;98=1;99=1;100=1;101=1;102=1;103=1;104=1;105=1;106=1;107=1;108=1;109=1;110=1;111=1;112=1;113=1;124=1;125=1;126=1;127=1;128=1;129=1;130=1;131=1;132=1;133=1,fromCore=false,storage=org.sonar.scanner.sensor.DefaultSensorStorage@4c212d2e,saved=false]`

Able to reproduce the same issue in DEV instance, the error is not occurring if we uninstall YAML analyser plugin.

**Comment by chas0amx** [comment]
Have the same on 9.6.1

**Comment by cedricfortin** [comment]
Same issue since I updated sonar to 9.6.1

**Comment by tonipepperoniuk** [comment]
Looks like native yaml support tripping you up https://community.sonarsource.com/t/can-not-add-the-same-measure-twice-on-sonarqube-9-6-1-yaml-plugin/71014

**Comment by e88z4** [comment]
Any update on this issue? We have been impacted with this bug as well. Sonarqube scanned my repo with AWS CloudFormation templates in it. Duplicates measurements were being generated from the native IaC Sonarqube plugin and sonar-yaml plugin.

**Comment by tonipepperoniuk** [comment]
> Any update on this issue? We have been impacted with this bug as well. Sonarqube scanned my repo with AWS CloudFormation templates in it. Duplicates measurements were being generated from the native IaC Sonarqube plugin and sonar-yaml plugin.

Hello. We just disabled the sonar-yaml plugin as we found our version (9.6.1) now has native support for all the languages we wish to scan. CloudFormation scanning is natively included with later versions of Sonarqube.

**Comment by e88z4** [comment]
> > Any update on this issue? We have been impacted with this bug as well. Sonarqube scanned my repo with AWS CloudFormation templates in it. Duplicates measurements were being generated from the native IaC Sonarqube plugin and sonar-yaml plugin.
> 
> Hello. We just disabled the sonar-yaml plugin as we found our version (9.6.1) now has native support for all the languages we wish to scan. CloudFormation scanning is natively included with later versions of Sonarqube.

Our organization has sonar-ansible plugin which has dependency on this plugin. Disabling sonar-yaml plugin is not an option.

**Comment by sbaudoin** [comment]
Hello. Sorry for the late reply. Do you have a sample YAML file to reproduce the issue, please?

**Comment by sbaudoin** [comment]
OK, so understood, I added some code to work this around
